-- Seeds the 50-item shop catalog. Run once, after migration_v3_shop.sql.

insert into chinese_shop_items (name_zh, name_en, category, price) values
('木劍', 'Wooden Sword', '武器', 15),
('石劍', 'Stone Sword', '武器', 30),
('鐵劍', 'Iron Sword', '武器', 55),
('金劍', 'Golden Sword', '武器', 70),
('鑽石劍', 'Diamond Sword', '武器', 100),
('木斧', 'Wooden Axe', '武器', 18),
('石斧', 'Stone Axe', '武器', 32),
('鐵斧', 'Iron Axe', '武器', 58),
('短弓', 'Short Bow', '武器', 40),
('長弓', 'Long Bow', '武器', 65),
('木鎬', 'Wooden Pickaxe', '工具', 16),
('石鎬', 'Stone Pickaxe', '工具', 28),
('鐵鎬', 'Iron Pickaxe', '工具', 52),
('金鎬', 'Golden Pickaxe', '工具', 68),
('鑽石鎬', 'Diamond Pickaxe', '工具', 95),
('木鏟', 'Wooden Shovel', '工具', 15),
('鐵鏟', 'Iron Shovel', '工具', 45),
('釣魚竿', 'Fishing Rod', '工具', 35),
('剪刀', 'Shears', '工具', 25),
('打火石', 'Flint and Steel', '工具', 20),
('皮革頭盔', 'Leather Helmet', '防具', 18),
('皮革胸甲', 'Leather Chestplate', '防具', 25),
('皮革護腿', 'Leather Leggings', '防具', 22),
('皮革靴子', 'Leather Boots', '防具', 16),
('鐵頭盔', 'Iron Helmet', '防具', 45),
('鐵胸甲', 'Iron Chestplate', '防具', 60),
('鐵護腿', 'Iron Leggings', '防具', 55),
('鐵靴子', 'Iron Boots', '防具', 40),
('金頭盔', 'Golden Helmet', '防具', 62),
('金胸甲', 'Golden Chestplate', '防具', 75),
('鑽石頭盔', 'Diamond Helmet', '防具', 85),
('鑽石胸甲', 'Diamond Chestplate', '防具', 100),
('紅色披風', 'Red Cape', '裝飾', 30),
('藍色披風', 'Blue Cape', '裝飾', 30),
('金色披風', 'Golden Cape', '裝飾', 70),
('牛仔帽', 'Cowboy Hat', '裝飾', 20),
('巫師帽', 'Wizard Hat', '裝飾', 45),
('皇冠', 'Crown', '裝飾', 90),
('太陽眼鏡', 'Sunglasses', '裝飾', 18),
('圍巾', 'Scarf', '裝飾', 15),
('背包裝飾', 'Decorative Backpack', '裝飾', 35),
('火把', 'Torch', '裝飾', 15),
('燈籠', 'Lantern', '裝飾', 22),
('盆栽', 'Potted Plant', '裝飾', 20),
('旗幟', 'Flag', '裝飾', 25),
('徽章', 'Badge', '裝飾', 15),
('氣球', 'Balloon', '裝飾', 15),
('風箏', 'Kite', '裝飾', 28),
('寵物蛋（小狼）', 'Pet Egg (Wolf)', '裝飾', 80),
('寵物蛋（小貓）', 'Pet Egg (Cat)', '裝飾', 80);
